### PR TITLE
Docker: adding some documentation

### PR DESCRIPTION
**Pull request by mvitaly**

### CODE REVIEW

**Comment by gto76** [comment]
Thanks.
Got to think a bit how to incorporate this info (I don't want it to clutter the readme and confuse people that are just skimming on one hand, but on the other I want it to be "for dummies"; what seems to be hard to combine. But I also don't want to totally exclude the info...)

**Comment by mvitaly** [comment]
Well, for me, I was looking for one command to run it.
Docker solves it. So for me it simplifies stuff.

Do you prefer to move it out of the readme?

**Comment by gto76** [comment]
No, I will include it, just maybe just one line...
Thing is that I did't yet managed to install docker on my system and I don't know few things:
For example when you run `./comp compile -n examples/hello-world` for example, can you then run this compiled binary (`./hello-world`)?

**Comment by gto76** [comment]
Aha I see, it only runs in interactive mode...

**Comment by gto76** [comment]
Aha I see, so it executes the command and then exits... Is there a way to use Docker as a classical terminal? I mean to save the files?

**Comment by gto76** [comment]
Thanks again, it's deferentially the easiest way to get started quickly...

**Pull request merged**
